### ISSUE TITLE
Sites A/B

### ISSUE THREAD

**Issue by moto-geek** [Azure/fedramp-iaas-webapp#70]
I was able to successfully install in US Govt Virginia region for my Site A. Per your notes Automation is only available in Virginia, so how do I deploy say a Site B. I tried editing pre-deploy to use US Texas. Was able to create the pre-deploy KeyVault Site B and Resource Group B, but when I tried to run the "Government Deploy" button template and Submit for deployment, I received an error in Azure.. 

The provided location 'usgovtexas' is not available for resource type 'Microsoft.Automation/automationAccounts'. List of available regions for the resource type is 'usgovvirginia'. (Code: LocationNotAvailableForResourceType)

Is there a way to use the automation service from Virginia to deploy to a different region as I have a requirement to do so?

**Comment by jomolesk** [comment]
An Automation account can take action on resources across regions (and even on non-Azure resources) even though the Automation service itself is only available in some regions. Since the full blueprint deployment includes provisioning of an Automation account, it will only work in regions where that service is available. You could deploy a B site in the Texas region (manually or by customizing and reusing some of the linked templates) and then add those resources to the Automation account in the Virginia region.
